# Generated by Django 2.1.7 on 2019-05-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listaprecios',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=256, null=True)),
                ('precio_producto', models.IntegerField(null=True)),
                ('categoria_producto', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('nombre_cliente', models.CharField(max_length=256, null=True)),
                ('comentario', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productosordenados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Listaprecios')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos_pedidos',
            field=models.ManyToManyField(to='tsuki_app.Productosordenados'),
        ),
    ]
