# Generated by Django 2.1.7 on 2019-05-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0002_auto_20190513_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='productos_pedidos',
        ),
        migrations.AddField(
            model_name='productosordenados',
            name='pedido',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Pedidos'),
            preserve_default=False,
        ),
    ]
