# Generated by Django 2.1.7 on 2019-05-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0003_auto_20190513_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosordenados',
            name='pedido',
        ),
    ]
