# Generated by Django 2.1.7 on 2019-05-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0004_remove_productosordenados_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosordenados',
            name='pedido',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Pedidos'),
        ),
    ]
