# Generated by Django 2.1.7 on 2019-05-14 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0006_auto_20190513_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosordenados',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Pedidos'),
        ),
    ]
